services:
  - type: web
    name: noticias-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application
