# Generated by Django 5.2.6 on 2025-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_interest_noticia_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_leitura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
