# Generated by Django 5.2.6 on 2025-11-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='leitura_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequência de Leitura'),
        ),
    ]
