# Generated by Django 5.2.6 on 2025-11-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticia_options_alter_perfil_leitura_streak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ultima_leitura',
            new_name='ultimo_checkin',
        ),
    ]
